### PR TITLE
Able to support Proxmox Mail Gateway (PMG)

### PR DESCRIPTION
**Pull request by ananiasfilho**
@gabrielcardoso21 from our team made changes to proxmoxer support PMG over https.
We included the service option so you can define service='PMG' or service='PVE'. By default service will use PVE service.
@jhollowe can you review this? thank you!

### CODE REVIEW

**Comment by morph027** [comment]
Looks good to me. Might be a good idea to add it to the SSH backend as well ...

**Comment by ananiasfilho** [comment]
If  team agree, i can check with my team to make it.

**Comment by jhollowe** [comment]
Thanks for this, it looks great! I agree that we should have this available for the SSH backends as well, but that can be another PR if we want to get this in (but no new version until the SSH is added).
I'm going to work a bit on trying to make this more modular and prep for all the backends supporting multiple services.

**Comment by jhollowe** [comment]
@ananiasfilho can you make sure "Allow edits from maintainers" is checked on this PR so I can add some commits?

**Comment by ananiasfilho** [comment]
@jhollowe its not show "Allow edits from maintainers" to me anymore. Have another method to continue?

**Comment by jhollowe** [comment]
It should be a checkbox in the right-side panel.

**Comment by ananiasfilho** [comment]
As i told you, its not showing to me. I know about it. but, disapear!

**Comment by ananiasfilho** [comment]
@jhollowe thanks! So, i will test PBS too, and if runs ok i will propose the ne merge. Remember PBS is BETA.
[pbs] Proxmox Backup Server - https://pbs.proxmox.com/wiki/index.php/Main_Page

**Pull request merged**
