### PR TITLE
Wip ipv6

### PR DESCRIPTION
**Pull request by dcasier**
Beginning of IPv6 Implementation

### CODE REVIEW

**Comment by jhollowe** [comment]
Forcing CI to activate

**Comment by jhollowe** [comment]
tested with ipv6 hosts in the following formats with PVE 7.1-2:
* "1234::5678"
* "[1234::5678]"
* "[1234::5687]:8006"

All connected successfully and the port specification worked correctly.

**Comment by jhollowe** [comment]
@dcasier was there anything else you were going to add to this?

**Review by jhollowe — APPROVED** [review]
LGTM

**Comment by dcasier** [comment]
> @dcasier was there anything else you were going to add to this?

Not at the moment

**Pull request merged**
