### PR TITLE
add automatic http backend session renewal

### PR DESCRIPTION
**Pull request by compilenix**
Caused by #9 (token expiration (http backend))

### CODE REVIEW

**Comment by morph027** [comment]
Thanks! Looks good.

How did you test it?

**Comment by compilenix** [comment]
I've manually tested this by running a script with an attached python debugger to get data from proxmox, after that wait at a breakpoint for a couple of hours and resumed execution.

Since then this code is running in my lab, encountered the renew-condition several times and raised not problems.

**Comment by jhollowe** [comment]
I'd like to not store the password unless we *really* have to.

I'm looking into the API's method of refreshing tokens. I would also like to try to keep core as backend agnostic as possible.

**Comment by jhollowe** [comment]
Resolved by #16

**Pull request closed without merging**
