### PR TITLE
Support CLI service

### LINKED ISSUE #76: Add support for local
Currently you are required to access a node "remotely" through its name. But if for some reason you want to run locally and do not want to use any type of authentication, this falls flat.

I would recommend to add a service for local, where it will do exactly like ssh, but using `Popen` instead for local access.

### PR DESCRIPTION
**Pull request by McTwist**
Fix #76.

### CODE REVIEW

**Comment by McTwist** [comment]
This uses `base_ssh` which makes some of the implementation a bit odd. Specifically the upload of a file and splitting of the command.

It should work without any issues, but it would be better to split up the cli part into `base_cli` and make `base_ssh` use that. That way we will separate the functionality and make it less awkward. I could create an issue for it after this is merged.

**Comment by jhollowe** [comment]
I really don't see a use case for a CLI backend. If you want to use Proxmoxer on a Proxmox node, you can just use one of the SSH backends with "localhost" as the host. And if you don't want to use SSH, you are already on the host and can just use the Proxmox CLI directly without needing to use Proxmoxer.

It doesn't really make sense to me to add an additional backend that will require maintenance and testing when a fully-functional method of doing the same thing already exists. Yes routing through SSH on localhost adds some amount of overhead, but Python and Proxmoxer are also not designed (or need to be) high performance.

If you have a specific reason for this, I'm all ears. But it seems like this is not needed.

**Comment by McTwist** [comment]
It's nothing with performance, but more about [a script I made](https://github.com/McTwist/vmctrl) which is run on the host itself. It currently uses the internal `qm` and `lxc` commands in order to tell which units to manage. I first intended to use `pvesh` directly, but liked your design so much that I wanted to be of some help to you by implementing what I am going to use.

**Comment by jhollowe** [comment]
I think for now we will stick with using SSH on localhost if on-node control is required. Thank you for the contribution though!

**Pull request closed without merging**
