### PR TITLE
Clean up SSH backends and add `local` backend.

### PR DESCRIPTION
**Pull request by reitermarkus**
Refactored and DRY'd the SSH backends and added a `local` backend as discussed in https://github.com/proxmoxer/proxmoxer/issues/76. Also improved argument handling by properly escaping shell commands passed to SSH backends since `subprocess.Popen` expects a list of args.

Closes https://github.com/proxmoxer/proxmoxer/issues/76.

### CODE REVIEW

**Comment by jhollowe** [comment]
So a few things:
* Thank you for contributing this PR!
* This PR (and its single commit) does a lot more than just add a local backend. It should be split into at least a commit for the local backend and SSH refactoring as well as one for all the other parts if you want them to be considered for addition.
* This really should not just be a single commit. You don't need to force-push everything to a single commit. If it needed to be a single commit in the main codebase, it could be squash committed. A key feature of git is to have smaller commits that each do a single logical thing.

I would like at least a commit for the refactoring of the SSH code to be more general and another commit for the local backend. Most of the other parts need to be considered separately. If you are able to do it, that would be great but if not I can work on it after some of the pending features I'm working on.

**Comment by reitermarkus** [comment]
Sure, I'll split this up into more meaningful commits.

**Comment by reitermarkus** [comment]
@jhollowe, should be a bit easier to review the individual parts now.

**Comment by reitermarkus** [comment]
@jhollowe, could you release a new version with this included?

**Comment by jhollowe** [comment]
Yeah, waiting for one last PR to get merged and then we will have version 1.3.0. I'm hoping this will come out today.

**Comment by reitermarkus** [comment]
Thanks!

**Pull request merged**
